### ISSUE TITLE
i got a SQL Error when start: ERROR: relation "queries" does not exist at character 979

### ISSUE THREAD

**Issue by chenlcme** [getredash/setup#18] opened 2021-02-05 12:59 UTC
The detail error logs

```text
scheduler_1         | [2021-02-05 12:55:02,083][PID:25][INFO][Beat] Scheduler: Sending due task sync_user_details (redash.tasks.sync_user_details)
scheduler_1         | [2021-02-05 12:55:02,085][PID:1][INFO][MainProcess] Received task: redash.tasks.sync_user_details[be809368-b74a-4e42-ac62-945db29f570b]   expires:[2021-02-05 12:55:47.083909+00:00]
scheduler_1         | [2021-02-05 12:55:02,087][PID:24][INFO][ForkPoolWorker-2] Task redash.tasks.sync_user_details[be809368-b74a-4e42-ac62-945db29f570b] succeeded in 0.000717621995136s: None
scheduler_1         | [2021-02-05 12:55:02,128][PID:25][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
scheduler_1         | [2021-02-05 12:55:02,130][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[389d1c89-af7e-41a7-aecf-585691e83607]  
scheduler_1         | [2021-02-05 12:55:02,132][PID:24][INFO][ForkPoolWorker-2] task_name=redash.tasks.refresh_queries task_id=389d1c89-af7e-41a7-aecf-585691e83607 Refreshing queries...
postgres_1          | ERROR:  relation "queries" does not exist at character 979
postgres_1          | STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
postgres_1          | 	FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
postgres_1          | 	WHERE queries.schedule IS NOT NULL ORDER BY queries.id
scheduler_1         | [2021-02-05 12:55:02,140][PID:24][ERROR][ForkPoolWorker-2] Task redash.tasks.refresh_queries[389d1c89-af7e-41a7-aecf-585691e83607] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) relation "queries" does not exist\nLINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...\n             ^\n',)
scheduler_1         | Traceback (most recent call last):
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
scheduler_1         |     R = retval = fun(*args, **kwargs)
scheduler_1         |   File "/app/redash/worker.py", line 84, in __call__
scheduler_1         |     return TaskBase.__call__(self, *args, **kwargs)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
scheduler_1         |     return self.run(*args, **kwargs)
scheduler_1         |   File "/app/redash/tasks/queries.py", line 184, in refresh_queries
scheduler_1         |     for query in models.Query.outdated_queries():
scheduler_1         |   File "/app/redash/models/__init__.py", line 555, in outdated_queries
scheduler_1         |     for query in queries:
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
scheduler_1         |     return self._execute_and_instances(context)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
scheduler_1         |     result = conn.execute(querycontext.statement, self._params)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
scheduler_1         |     return meth(self, multiparams, params)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
scheduler_1         |     return connection._execute_clauseelement(self, multiparams, params)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
scheduler_1         |     compiled_sql, distilled_params
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
scheduler_1         |     context)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
scheduler_1         |     exc_info
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
scheduler_1         |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
scheduler_1         |     context)
scheduler_1         |   File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
scheduler_1         |     cursor.execute(statement, parameters)
scheduler_1         | ProgrammingError: (psycopg2.ProgrammingError) relation "queries" does not exist
scheduler_1         | LINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...
scheduler_1         |              ^
scheduler_1         |  [SQL: 'SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at \nFROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id \nWHERE queries.schedule IS NOT NULL ORDER BY queries.id'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by ainsofs** [comment] 2021-09-26 23:22
I had the same error. It seems to be caused by a missing database. Running this fixed it for me

`docker-compose run --rm server create_db`

Which is part of the setup.sh script https://github.com/getredash/setup/blob/b9ee472e57b0bb78e81f0bb187e5d46e4cb02a47/setup.sh#L114

**Comment by justinclift** [comment] 2024-03-24 14:42
Closing this now, as it seems really old + @ainsofs's suggestion is probably the right solution anyway. :smile:

@ainsofs Note that I adjusted the url you were pointing to there, so it references the script using a fixed point in time.  Shouldn't break now whenever the script gets changed. :smile:

**Closed as completed by justinclift** 2024-03-24 14:42 UTC
