### ISSUE TITLE
/opt/redash/setup.sh: 22: USER: parameter not set

### ISSUE THREAD

**Issue by girishchavanbytemark** [getredash/setup#33] opened 2022-03-22 10:06 UTC
I am getting this error when I run setup.sh, Actually I am using Dockerfile to run this script taking Docker machine locally using 

`docker build . -t redashtest`

My Dockerfile:
`FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    sudo \
    curl 

RUN adduser --system --no-create-home --disabled-login --gecos "" redash
 
COPY setup.sh /opt/redash/

RUN /bin/sh /opt/redash/setup.sh`

Error : 

```
100   664  100   664    0     0    402      0  0:00:01  0:00:01 --:--:--   402
100 11.2M  100 11.2M    0     0   703k      0  0:00:16  0:00:16 --:--:-- 2305k
#9 119.6 /opt/redash/setup.sh: 22: USER: parameter not set
------
executor failed running [/bin/sh -c /bin/sh /opt/redash/setup.sh]: exit code: 2
```

**Comment by girishchavanbytemark** [comment] 2022-03-22 15:41
I got resolved with the above issue by adding root user, The new error I can see is :

```
#11 106.9 Couldn't connect to Docker daemon at http+docker://localhost - is it running?
#11 106.9 
#11 106.9 If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**Comment by justinclift** [comment] 2024-03-24 14:22
Closing this as there doesn't seem to be something that we need to do (?), and the issue is quite old now.

---

As a note, we significantly updated the setup.sh script yesterday to make it work on a wider range of Linux distro's.  If/when you need to run Redash again, the setup.sh script may be all you need to get things going.

**Closed as completed by justinclift** 2024-03-24 14:22 UTC
